<?php
/*
 * @file
 */
include_once 'spads_sites.inc';

/**
 * Implementatiof of hook_block_info
 */
function spads_sites_block_info(){
  return array(
    '0' => array(
      'info' => 'Scratchpads.eu map block',
      'cache' => DRUPAL_NO_CACHE
    ),
    '1' => array(
      'info' => 'Scratchpads.eu stats block',
      'cache' => DRUPAL_NO_CACHE
    )
  );
}

/**
 * Implementation of hook_block_view
 */
function spads_sites_block_view($delta = 0){
  switch($delta){
    case 0:
      $query = db_select('users_roles', 'u')->condition('rid', 4)->countQuery();
      $number_of_ambassadors = $query->execute()->fetchField();
      return array(
        'subject' => 'Scratchpads around the world',
        'content' => "<p><strong>" . number_format(variable_get('scratchpads_total_sites', 0), 0, '.', ',') . "</strong> " . "Scratchpads by <strong>" . number_format(variable_get('scratchpads_total_users', 0), 0, '.', ',') . "</strong> " . "active users covering <strong>" . number_format(variable_get('scratchpads_total_taxa', 0), 0, '.', ',') . "</strong> " . "taxa in <strong>" . number_format(variable_get('scratchpads_total_pages', 0), 0, '.', ',') . "</strong> pages.</p>" . "<p>Our " . $number_of_ambassadors . " Scratchpads ambassadors are located across the globe:</p>"
      );
      break;
    case 1:
      return array(
        'subject' => 'General statistics',
        'content' => "<table><tr><th>Number of Scratchpads</th><td>" . number_format(variable_get('scratchpads_total_sites', 0), 0, '.', ' ') . "</td></tr><tr><th>Total number of page views</th><td>" . number_format(variable_get('scratchpads_total_views', 0), 0, '.', ' ') . "</td></tr><tr><th>Total number of pages</th><td>" . number_format(variable_get('scratchpads_total_pages', 0), 0, '.', ' ') . "</td></tr><tr><th>Total number of users</th><td>" . number_format(variable_get('scratchpads_total_users', 0), 0, '.', ' ') . "</td></tr></table>"
      );
  }
}

/**
 * Implementation of hook_cron
 */
function spads_sites_cron(){
  // Fetch the stats data
  $data = _spads_sites_load_data(SPADS_SITES_URL);
  // Update existing nodes,and create new nodes
  foreach($data as $row){
    $node = _spads_sites_find_site($row['site_url']);
    _spads_sites_set_node_data($node, $row);
    node_save($node);
  }
  // Purge sites that have disapeared
  _spads_sites_purge($data);
  // Rebuild stats
  _spads_sites_statistics();
}
